Fix the Python array problem
This line fixes the following error raised when using Python 3.12.

/home/aakyuz/miniconda3/envs/inj_test_fir/lib/python3.12/site-packages/pycbc/psd/variation.py:38: RuntimeWarning: divide by zero encountered in power
          fweight = freqs ** (-7./6.) * filt / numpy.sqrt(plong)
        Traceback (most recent call last):
          File "/home/aakyuz/repo/fir/pycbc/bin/pycbc_inspiral_fir", line 384, in <module>
            main()
          File "/home/aakyuz/repo/fir/pycbc/bin/pycbc_inspiral_fir", line 379, in main
            event_mgr.write_events(args.output)
          File "/home/aakyuz/miniconda3/envs/inj_test_fir/lib/python3.12/site-packages/pycbc/events/eventmgr.py", line 483, in write_events
            self.write_to_hdf(outname)
          File "/home/aakyuz/miniconda3/envs/inj_test_fir/lib/python3.12/site-packages/pycbc/events/eventmgr.py", line 586, in write_to_hdf
            numpy.array([float(temps_per_core) * float(time_ratio)])
                                                 ^^^^^^^^^^^^^^^^^
        TypeError: only 0-dimensional arrays can be converted to Python scalar